<a href="https://colab.research.google.com/github/mamenaca/curso_python_esp_estadistica/blob/main/unidad3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import copy as cp
import math
import funciones
import matplotlib.pyplot as plt


In [ ]:
f=cp.deepcopy(g)

#NUMPY: Numeric Python





*   Los elementos son matrices como en matlab, se pueden aplicar operaciones punto a punto fácilmente
*   Comunidad de software libre. NUMFOCUS - Sponsored projects

Instalación del paquete en el local: pip install numpy

In [38]:
import numpy # Es decir, lo tengo

In [39]:
numpy.__version__

'1.21.6'

La versión en colab se puede actualizar. Verificar última versión

In [41]:
!pip install numpy==1.3.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 2.0 MB 2.8 MB/s 
ERROR: Could not find a version that satisfies the requirement numpy==1.3.0 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0rc1, 1.20.0rc2, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0rc1, 1.21.0rc2, 1.21.0, 1.21.1, 1.2

Es posible importar cualquier paquete con un alias, para agilizar la escritura

In [ ]:
import numpy as np #muy común

#Arreglo numpy vs arreglo python

In [1]:
(1,2)+(1,4)

(1, 2, 1, 4)

In [2]:
[1,3]+[4,4]

[1, 3, 4, 4]

In [42]:
a=[2,4]
b=[3,5]


In [43]:
import numpy

In [6]:
aN=numpy.array(a)
bN=numpy.array(b)
aN,bN

(array([2, 4]), array([3, 5]))

In [7]:
aN+bN

array([5, 9])

#En un numpy array todos los elementos se convierten al tipo de dato más general: str,float, int, bool

In [8]:
c=numpy.array(["2",3,5.1])

In [9]:
c

array(['2', '3', '5.1'], dtype='<U32')

In [10]:
d=numpy.array([2,3,5.1])

In [11]:
d

array([2. , 3. , 5.1])

In [44]:
e=numpy.array([True,3,5,6,False])

In [45]:
e

array([1, 3, 5, 6, 0])

#Escoger el tipo de dato en el numpy array

Dada la estructura de datos de numpy, similar a las matrices de matlab, no tiene mucho sentido convertir los datos en un tipo que no sea int o float

In [14]:
f=numpy.array([True,3,5,6],dtype=float)
numpy.array()

array([1., 3., 5., 6.])

#Indexación de un numpy array. Recibe la misma forma de las listas pero, tiene su propia indexación:

In [75]:
g=numpy.random.uniform(0,100,(2,2,2,3))

In [56]:
numpy.random.normal?

In [71]:
g

array([[64.09709416, 30.77377868],
       [72.56357869, 41.07472077]])

In [60]:
g[0:2][0:2]

array([[31.812664  , 93.33995416, 83.51971729, 71.32984454],
       [87.15412555, 78.72295367, 46.79413454, 14.39814041]])

In [57]:
g[0,0]

31.81266399969346

#Slicing como en listas y tuplas: NUNCA se toma el último

In [67]:
g[0:2,0:2]

array([[31.812664  , 93.33995416],
       [87.15412555, 78.72295367]])

#Mutabilidad de los arreglos numpy

In [21]:
g

array([[64.53795763, 28.56692908, 56.34730136, 90.09352675],
       [79.6360474 , 13.44195718, 62.4341283 , 45.3939936 ],
       [22.72787952, 72.3002332 ,  4.96010138, 64.12691793],
       [11.81407198, 51.99716908,  9.9014559 , 87.87338414]])

In [22]:
g[0,0]=1555

In [23]:
g

array([[1555.        ,   28.56692908,   56.34730136,   90.09352675],
       [  79.6360474 ,   13.44195718,   62.4341283 ,   45.3939936 ],
       [  22.72787952,   72.3002332 ,    4.96010138,   64.12691793],
       [  11.81407198,   51.99716908,    9.9014559 ,   87.87338414]])

#Copia de arreglos numpy. Aplica el método copy(), pero como internamente es una lista de listas, conviene usar deepcopy

In [24]:
copiag=g

In [25]:
id(g),id(copiag)

(139901473760528, 139901473760528)

In [27]:
copiag=g.copy()
id(g),id(copiag)

(139901473760528, 139901473627184)

#Ojo, los slices ("pedazos") de arreglo tiene ubicación propia en memoria

In [28]:
id(g[0:1,0:2]),id(copiag[0:1,0:2]),

(139901473674992, 139901473674992)

¡Falló usando el copy()! Se puede solucionar haciendo copias de los pedazos

In [29]:
pedazo=copiag[0:1,0:2].copy()
id(g[0:1,0:2]),id(pedazo),

(139901473799504, 139901473800080)

#convertir listas en matrices: Debe ser una lista de lista que sea simétrica

In [73]:
M=numpy.array([[1,3,4],[9,8,44]])

In [37]:
M

array([[ 1,  3,  4],
       [ 9,  8, 44]])

#.shape()

In [74]:
M.shape

(2, 3)

In [76]:
g.shape

(2, 2, 2, 3)

In [77]:
print(g)

[[[[81.15427633 12.38501524 60.25089194]
   [27.7866754  21.02407328 90.75260041]]

  [[89.33720311 68.98387765 19.66304723]
   [79.95340472 14.46242186 63.50743351]]]


 [[[74.42250271 15.42175667 47.96409694]
   [35.68582074 64.49199317 74.91478101]]

  [[97.8129129  27.84232069 89.52276718]
   [42.73016996 50.83286412 56.83612699]]]]


#¿len()?

In [78]:
len(g)

2

In [88]:
ff=g.sum(axis=0)
ff.shape

(2, 2, 3)

In [89]:
gg=ff.sum(axis=2)
gg.shape

(2, 2)

In [90]:
gg

array([[291.59853984, 314.65594402],
       [393.16212876, 308.32242117]])

In [91]:
gg.sum(axis=0)

array([684.76066861, 622.97836519])

In [92]:
291.59853984+393.16212876

684.7606685999999

In [ ]:
gg.

#linspace(inicio, fin, número de datos)

In [95]:
arr=numpy.linspace(0,10,10)

In [96]:
print(arr[-1],arr[0])

10.0 0.0


#reshape(dim1,dim2,dim3,dim....)

In [97]:
g

array([[[[81.15427633, 12.38501524, 60.25089194],
         [27.7866754 , 21.02407328, 90.75260041]],

        [[89.33720311, 68.98387765, 19.66304723],
         [79.95340472, 14.46242186, 63.50743351]]],


       [[[74.42250271, 15.42175667, 47.96409694],
         [35.68582074, 64.49199317, 74.91478101]],

        [[97.8129129 , 27.84232069, 89.52276718],
         [42.73016996, 50.83286412, 56.83612699]]]])

In [111]:
g.shape

(2, 2, 2, 3)

In [113]:
g.reshape(3,4,2)

array([[[81.15427633, 12.38501524],
        [60.25089194, 27.7866754 ],
        [21.02407328, 90.75260041],
        [89.33720311, 68.98387765]],

       [[19.66304723, 79.95340472],
        [14.46242186, 63.50743351],
        [74.42250271, 15.42175667],
        [47.96409694, 35.68582074]],

       [[64.49199317, 74.91478101],
        [97.8129129 , 27.84232069],
        [89.52276718, 42.73016996],
        [50.83286412, 56.83612699]]])

In [106]:
h=numpy.array([[2,5],[55,7],[31,82],[5,22]])
h

array([[ 2,  5],
       [55,  7],
       [31, 82],
       [ 5, 22]])

In [107]:
h.shape

(4, 2)

In [110]:
h.reshape(2,2,2)

array([[[ 2,  5],
        [55,  7]],

       [[31, 82],
        [ 5, 22]]])

#ones(), zeros()

In [117]:
numpy.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [118]:
numpy.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#Matriz Identidad

In [122]:
numpy.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [123]:
h

array([[ 2,  5],
       [55,  7],
       [31, 82],
       [ 5, 22]])

#Matriz transpuesta

Inversión de los ejes

In [127]:
h.transpose(0,1)

array([[ 2,  5],
       [55,  7],
       [31, 82],
       [ 5, 22]])

In [126]:
h.transpose?

In [136]:
g.shape

(2, 2, 2, 3)

In [135]:
g.transpose(1,3,2,0)

array([[[[81.15427633, 74.42250271],
         [27.7866754 , 35.68582074]],

        [[12.38501524, 15.42175667],
         [21.02407328, 64.49199317]],

        [[60.25089194, 47.96409694],
         [90.75260041, 74.91478101]]],


       [[[89.33720311, 97.8129129 ],
         [79.95340472, 42.73016996]],

        [[68.98387765, 27.84232069],
         [14.46242186, 50.83286412]],

        [[19.66304723, 89.52276718],
         [63.50743351, 56.83612699]]]])

In [139]:
h.T

array([[ 2, 55, 31,  5],
       [ 5,  7, 82, 22]])

#Ajuste polinomial

In [143]:
x=numpy.arange(0,10)
y=4*x**2

In [144]:
x,y

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324]))

In [145]:
numpy.polyfit(x,y,2)#betas- coeficientes

array([ 4.00000000e+00, -2.30470946e-14,  6.14913662e-14])

In [ ]:
Scipy

#Indexación booleana: Filtros-Máscaras

#Ejercicios



*   Sea x un areglo de números aleatorios , dist unif, entre -1 y 1. comprueben que la media es cero
*   sistema de ecuaciones
*   sumar todos los números de un arreglo numpy divisibles por 7 pero no divisibles por 5

